<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIaXwKAP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIaXwKAP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIaXwKAP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIaXwKAP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIaXwKAP\App_KernelDevDebugContainer([
    'container.build_hash' => 'IaXwKAP',
    'container.build_id' => '70da1869',
    'container.build_time' => 1589458705,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIaXwKAP');
