<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4iAPyng\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4iAPyng/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4iAPyng.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4iAPyng\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4iAPyng\App_KernelDevDebugContainer([
    'container.build_hash' => '4iAPyng',
    'container.build_id' => 'e6ab76ec',
    'container.build_time' => 1589529292,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4iAPyng');
