<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1RrnYLf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1RrnYLf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1RrnYLf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1RrnYLf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1RrnYLf\App_KernelDevDebugContainer([
    'container.build_hash' => '1RrnYLf',
    'container.build_id' => 'a22151a1',
    'container.build_time' => 1589468253,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1RrnYLf');
