<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'app_app_home' => [['_locale'], ['_controller' => 'App\\Controller\\AppController::home'], [], [['text', '/'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'app_beer_new' => [['_locale'], ['_controller' => 'App\\Controller\\BeerController::new'], [], [['text', '/beer/add'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'app_beer_index' => [['_locale', 'page'], ['page' => 1, '_controller' => 'App\\Controller\\BeerController::index'], ['page' => '\\d+'], [['variable', '/', '\\d+', 'page', true], ['text', '/beer/index'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'app_beer_edit' => [['_locale', 'id'], ['_controller' => 'App\\Controller\\BeerController::edit'], ['id' => '\\d+'], [['text', '/edit'], ['variable', '/', '\\d+', 'id', true], ['text', '/beer'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'app_beer_delete' => [['_locale', 'id'], ['_controller' => 'App\\Controller\\BeerController::delete'], ['id' => '\\d+'], [['text', '/delete'], ['variable', '/', '\\d+', 'id', true], ['text', '/beer'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'app_beer_show' => [['_locale', 'id'], ['_controller' => 'App\\Controller\\BeerController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/beer'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
];
